from __future__ import annotations

from typing import Any, Protocol

from .models import CharacterAsset, CharacterImageAssistantConfig, MusicAsset, ProviderConfig, RenderJob, SceneJob, StoryAssistantConfig, VisualAsset, VoiceAsset


class RenderJobRepository(Protocol):
    def create(self, job: RenderJob) -> None: ...
    def get(self, job_id: str) -> RenderJob | None: ...
    def list_recent(self, limit: int = 30) -> list[RenderJob]: ...
    def patch(self, job_id: str, **fields: Any) -> None: ...
    def delete(self, job_id: str) -> RenderJob | None: ...
    def list_ready_for_composition(self, limit: int = 10) -> list[RenderJob]: ...
    def refresh_status(self, job_id: str) -> RenderJob | None: ...


class SceneJobRepository(Protocol):
    def create_many(self, scene_jobs: list[SceneJob]) -> None: ...
    def get(self, scene_job_id: str) -> SceneJob | None: ...
    def list_for_job(self, job_id: str) -> list[SceneJob]: ...
    def list_by_status(self, statuses: list[str], limit: int = 20) -> list[SceneJob]: ...
    def patch(self, scene_job_id: str, **fields: Any) -> None: ...


class ProviderConfigRepository(Protocol):
    def list_all(self) -> list[ProviderConfig]: ...
    def get(self, provider_code: str) -> ProviderConfig | None: ...
    def upsert(self, config: ProviderConfig) -> ProviderConfig: ...
    def seed(self, config: ProviderConfig) -> None: ...


class StoryAssistantConfigRepository(Protocol):
    def list_all(self) -> list[StoryAssistantConfig]: ...
    def get(self, assistant_code: str) -> StoryAssistantConfig | None: ...
    def upsert(self, config: StoryAssistantConfig) -> StoryAssistantConfig: ...
    def seed(self, config: StoryAssistantConfig) -> None: ...


class CharacterImageAssistantConfigRepository(Protocol):
    def list_all(self) -> list[CharacterImageAssistantConfig]: ...
    def get(self, assistant_code: str) -> CharacterImageAssistantConfig | None: ...
    def upsert(self, config: CharacterImageAssistantConfig) -> CharacterImageAssistantConfig: ...
    def seed(self, config: CharacterImageAssistantConfig) -> None: ...


class AssetRepository(Protocol):
    def list_assets(self, asset_type: str, enabled_only: bool = True) -> list[dict[str, Any]]: ...
    def list_grouped(self, enabled_only: bool = True) -> dict[str, list[dict[str, Any]]]: ...
    def create_asset(self, asset_type: str, payload: dict[str, Any]) -> dict[str, Any]: ...
    def update_asset(self, asset_type: str, asset_id: str, payload: dict[str, Any]) -> dict[str, Any]: ...
    def delete_asset(self, asset_type: str, asset_id: str) -> dict[str, Any] | None: ...
    def get_asset(self, asset_type: str, asset_id: str) -> dict[str, Any] | None: ...


class StorageService(Protocol):
    def save_bytes(self, *, filename: str, data: bytes, category: str): ...
    def delete(self, path: str) -> None: ...
    def exists(self, path: str) -> bool: ...
    def to_public_url(self, path: str) -> str: ...
